package dhcp

// Standard options (RFC1533)
const (
  OPT_PAD byte = iota
  OPT_SUBNET_MASK // 0x01, 4, net.IP
  OPT_TIME_OFFSET // 0x02, 4, int32 (signed seconds from UTC)
  OPT_DEFAULT_GATEWAY // 0x03, n*4, [n]net.IP
  OPT_TIME_SERVER // 0x04, n*4, [n]net.IP
  OPT_NAME_SERVER // 0x05, n*4, [n]net.IP
  OPT_DOMAIN_NAME_SERVERS // 0x06, n*4, [n]net.IP
  OPT_LOG_SERVER // 0x07, n*4, [n]net.IP
  OPT_COOKIE_SERVER // 0x08, n*4, [n]net.IP
  OPT_LPR_SERVER // 0x09, n*4, [n]net.IP
  OPT_IMPRESS_SERVER // 0x0a, n*4, [n]net.IP
  OPT_RLSERVER // 0x0b, n*4, [n]net.IP 
  OPT_HOST_NAME // 0x0c, n, string
  OPT_BOOTFILE_SIZE // 0x0d, 2, uint16
  OPT_MERIT_DUMP_FILE // 0x0e, >1, string
  OPT_DOMAIN_NAME // 0x0f, n, string
  OPT_SWAP_SERVER // 0x10, n*4, [n]net.IP
  OPT_ROOT_PATH   // 0x11, n, string
  OPT_EXTENSIONS_PATH // 0x12, n, string
  OPT_IP_FORWARDING // 0x13, 1, bool
  OPT_SOURCE_ROUTING // 0x14, 1, bool
  OPT_POLICY_FILTER // 0x15, 8*n, [n]{net.IP/net.IP}
  OPT_DGRAM_MTU // 0x16, 2, uint16
  OPT_DEFAULT_TTL // 0x17, 1, byte
  OPT_PATH_MTU_AGING_TIMEOUT // 0x18, 4, uint32
  OPT_PATH_PLATEU_TABLE_OPTION // 0x19, 2*n, []uint16
  OPT_INTERFACE_MTU //0x1a, 2, uint16
  OPT_ALL_SUBS_LOCAL // 0x1b, 1, bool
  OPT_BROADCAST_ADDR // 0x1c, 4, net.IP
  OPT_MASK_DISCOVERY // 0x1d, 1, bool
  OPT_MASK_SUPPLIER  // 0x1e, 1, bool
  OPT_ROUTER_DISCOVERY // 0x1f, 1, bool
  OPT_ROUTER_SOLICIT_ADDR // 0x20, 4, net.IP
  OPT_STATIC_ROUTE // 0x21, n*8, [n]{net.IP/net.IP} -- note the 2nd is router not mask 
  OPT_ARP_TRAILERS // 0x22, 1, bool
  OPT_ARP_TIMEOUT  // 0x23, 4, uint32
  OPT_ETHERNET_ENCAP // 0x24, 1, bool
  OPT_TCP_TTL // 0x25,1, byte
  OPT_TCP_KEEPALIVE_INT // 0x26,4, uint32
  OPT_TCP_KEEPALIVE_GARBAGE // 0x27,1, bool
  OPT_NIS_DOMAIN // 0x28,n, string
  OPT_NIS_SERVERS // 0x29,4*n,  [n]net.IP
  OPT_NTP_SERVERS // 0x2a, 4*n, [n]net.IP
  OPT_VENDOR_OPT // 0x2b, n, [n]byte // may be encapsulated.
  OPT_NETBIOS_IPNS // 0x2c, 4*n, [n]net.IP
  OPT_NETBIOS_DDS // 0x2d, 4*n, [n]net.IP
  OPT_NETBIOS_NODE_TYPE // 0x2e, 1, magic byte
  OPT_NETBIOS_SCOPE // 0x2f, n, string
  OPT_X_FONT_SERVER // 0x30, n, string
  OPT_X_DISPLAY_MANAGER // 0x31, n, string

  OPT_SIP_SERVERS byte = 0x78 // 0x78!, n, url
  OPT_END byte = 0xff
)


// I'm amazed that this is syntactically valid.
// cool though.
var OptionTypeStrings = [256]string{
 OPT_PAD: "(padding)",
 OPT_SUBNET_MASK: "SubnetMask",
 OPT_TIME_OFFSET: "TimeOffset",
 OPT_DEFAULT_GATEWAY: "DefaultGateway",
 OPT_TIME_SERVER: "rfc868", // old time server protocol, stringified to dissuade confusion w. NTP
 OPT_NAME_SERVER: "ien116", // obscure nameserver protocol, stringified to dissuade confusion w. DNS
 OPT_DOMAIN_NAME_SERVERS: "DNS",
 OPT_LOG_SERVER: "mitLCS",  // MIT LCS server protocol, yada yada w. Syslog
 OPT_COOKIE_SERVER: "OPT_COOKIE_SERVER",
 OPT_LPR_SERVER: "OPT_LPR_SERVER",
 OPT_IMPRESS_SERVER: "OPT_IMPRESS_SERVER",
 OPT_RLSERVER: "OPT_RLSERVER",
 OPT_HOST_NAME: "Hostname",
 OPT_BOOTFILE_SIZE: "BootfileSize",
 OPT_MERIT_DUMP_FILE: "OPT_MERIT_DUMP_FILE",
 OPT_DOMAIN_NAME: "DomainName",
 OPT_SWAP_SERVER: "OPT_SWAP_SERVER",
 OPT_ROOT_PATH: "RootPath",
 OPT_EXTENSIONS_PATH: "OPT_EXTENSIONS_PATH",
 OPT_IP_FORWARDING: "OPT_IP_FORWARDING",
 OPT_SOURCE_ROUTING: "OPT_SOURCE_ROUTING",
 OPT_POLICY_FILTER: "OPT_POLICY_FILTER",
 OPT_DGRAM_MTU: "OPT_DGRAM_MTU",
 OPT_DEFAULT_TTL: "OPT_DEFAULT_TTL",
 OPT_PATH_MTU_AGING_TIMEOUT: "OPT_PATH_MTU_AGING_TIMEOUT",
 OPT_PATH_PLATEU_TABLE_OPTION: "OPT_PATH_PLATEU_TABLE_OPTION",
 OPT_INTERFACE_MTU: "OPT_INTERFACE_MTU",
 OPT_ALL_SUBS_LOCAL: "OPT_ALL_SUBS_LOCAL",
 OPT_BROADCAST_ADDR: "OPT_BROADCAST_ADDR",
 OPT_MASK_DISCOVERY: "OPT_MASK_DISCOVERY",
 OPT_MASK_SUPPLIER: "OPT_MASK_SUPPLIER",
 OPT_ROUTER_DISCOVERY: "OPT_ROUTER_DISCOVERY",
 OPT_ROUTER_SOLICIT_ADDR: "OPT_ROUTER_SOLICIT_ADDR",
 OPT_STATIC_ROUTE: "OPT_STATIC_ROUTE",
 OPT_ARP_TRAILERS: "OPT_ARP_TRAILERS",
 OPT_ARP_TIMEOUT: "OPT_ARP_TIMEOUT",
 OPT_ETHERNET_ENCAP: "OPT_ETHERNET_ENCAP",
 OPT_TCP_TTL: "OPT_TCP_TTL",
 OPT_TCP_KEEPALIVE_INT: "OPT_TCP_KEEPALIVE_INT",
 OPT_TCP_KEEPALIVE_GARBAGE: "OPT_TCP_KEEPALIVE_GARBAGE",
 OPT_NIS_DOMAIN: "OPT_NIS_DOMAIN",
 OPT_NIS_SERVERS: "OPT_NIS_SERVERS",
 OPT_NTP_SERVERS: "OPT_NTP_SERVERS",
 OPT_VENDOR_OPT: "OPT_VENDOR_OPT",
 OPT_NETBIOS_IPNS: "OPT_NETBIOS_IPNS",
 OPT_NETBIOS_DDS: "OPT_NETBIOS_DDS",
 OPT_NETBIOS_NODE_TYPE: "OPT_NETBIOS_NODE_TYPE",
 OPT_NETBIOS_SCOPE: "OPT_NETBIOS_SCOPE",
 OPT_X_FONT_SERVER: "OPT_X_FONT_SERVER",
 OPT_X_DISPLAY_MANAGER: "OPT_X_DISPLAY_MANAGER",
 OPT_END: "(end)",
 OPT_SIP_SERVERS: "SipServers",
 DHCPOPT_REQUEST_IP: "RequestIP",
 DHCPOPT_LEASE_TIME: "LeaseTime",
 DHCPOPT_EXT_OPTS:   "ExtOpts",
 DHCPOPT_MESSAGE_TYPE:  "MessageType",
 DHCPOPT_SERVER_ID:     "ServerID",
 DHCPOPT_PARAMS_REQUEST: "ParamsRequest",
 DHCPOPT_MESSAGE:        "Message",
 DHCPOPT_MAX_DHCP_SIZE:  "MaxDHCPSize",
 DHCPOPT_T1:             "Timer1",
 DHCPOPT_T2:             "Timer2",
 DHCPOPT_CLASS_ID:       "ClassID",
 DHCPOPT_CLIENT_ID:      "ClientID",
}
